services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000" # for chat-ui
    command: uvicorn src.rag.api:app --host 0.0.0.0 --port 8000 # for chat-ui

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
      ME_CONFIG_BASICAUTH: false

  postgres:
    image: postgres:17
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # This variable holds the comma-separated list of databases to create.
      # e.g POSTGRES_MULTIPLE_DATABASES: db1,db2,db3
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_DB_REASONING_ERRORS}
      POSTGRES_DEFAULT_USER_PASSWORD: ${POSTGRES_DEFAULT_USER_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres

  prefect:
    image: prefecthq/prefect:2-python3.12
    ports:
      - "4200:4200"
    environment:
      PREFECT_API_URL: ${PREFECT_API_URL}
    volumes:
      - prefect-data:/root/.prefect
    command: prefect server start --host 0.0.0.0

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage

  chat-ui:
    build:
      context: .
      dockerfile: docker/Dockerfile.chat-ui
      args:
        - NEXT_PUBLIC_FASTAPI_URL=${NEXT_PUBLIC_FASTAPI_URL}
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_FASTAPI_URL: ${NEXT_PUBLIC_FASTAPI_URL}
    depends_on:
      - app

  neo4j:
    image: neo4j:latest
    restart: always
    ports:
      - "7474:7474"   # HTTP
      - "7687:7687"   # Bolt
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
    volumes:
      - neo4j_data:/data

configs:
  qdrant_config:
    content: |
      log_level: INFO

volumes:
  mongodb_data:
  postgres_data:
  prefect-data:
  neo4j_data:
